In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
squareroot = np.sqrt(arr)
print(squareroot)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [ ]:
import numpy as np
arr = np.array([1,3,4,5,6,2])
print(np.sort(arr))

[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr = np.array([9,9,5,6,5,4])
uni = np.unique(arr)
print(uni)


[4 5 6 9]


In [ ]:
import numpy as np
war = np.identity(7)
print(war)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
arr = np.array([1,2,np.nan,4])
print(arr)
arr[2] = 3
print(arr)

[ 1.  2. nan  4.]
[1. 2. 3. 4.]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr = arr.reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr = np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [ ]:
import numpy as np
arr = np.full((4,5),'mehak')
print(arr)

[['mehak' 'mehak' 'mehak' 'mehak' 'mehak']
 ['mehak' 'mehak' 'mehak' 'mehak' 'mehak']
 ['mehak' 'mehak' 'mehak' 'mehak' 'mehak']
 ['mehak' 'mehak' 'mehak' 'mehak' 'mehak']]


In [ ]:
import numpy as np
arr = np.array([[9,8,5,4],[2,4,3,4]])
tracing = np.trace(arr)
print(tracing)

13


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
mee = np.ptp(arr)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
#important
arr = np.array([[23,34,28,38],[82,73,56,22]])
transpose = arr.T
print(transpose)

[[23 82]
 [34 73]
 [28 56]
 [38 22]]


In [ ]:
pip install pandas

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
product = np.prod(arr)
print(product)

40320


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
ss = np.std(arr)
print(arr)
#standard deviation


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
a = np.array([11,13,15])
b = np.array([10,50,70])
mean = np.mean(a)
mean1 = np.mean(b)
print(mean)
print(mean1)
standard_deviation = np.std(a)
std1 = np.std(b)
print(standard_deviation)
#standard deviation  means how much far away from each other our data is and how much far away the points are from the mean
print(std1)


13.0
43.333333333333336
1.632993161855452
24.94438257849294


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
aa = np.ravel(arr)
print(aa)

[1 2 3 4 5]


In [ ]:
import numpy as np
char a = np.array(['@', '#', '$'], dtype='Ul')
print(arr)

SyntaxError: invalid syntax (ipython-input-3129838279.py, line 2)

Replace `pandas` with the name of the library you want to install. You can also specify a version or extra features like this:
```
!pip install 'tensorflow-gpu==2.5.0'
!pip install 'opencv-python[contrib]'
```